### ISSUE TITLE
Stable URL to the latest release files

### ISSUE THREAD

**Issue by dracon80** [smallstep/cli#1028]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When creating a script to download step-cli the URL for the download includes the version number. While this is great for being able to download a specific version it would be most helpful if there was a simple link to the latest version such as below.

https://dl.smallstep.com/gh-release/cli/gh-release-header/latest/step-cli_amd64.deb

## Why is this needed?
It would make downloading the latest version using a script or any static link for that matter much easier.

**Comment by hslatman** [comment]
Hi @dracon80, we recently made some changes to the process, and it's now possible to obtain the latest release using an URL like the following: https://github.com/smallstep/cli/releases/latest/download/step-cli_amd64.deb

**Comment by tashian** [comment]
Hi @dracon80,

The [step-cli install documentation](https://smallstep.com/docs/step-cli/installation/) contains unversioned links.
The links in the GitHub release notes are versioned, because we want to preserve those links over time.
Older release note links should link to older versions of the software, not the latest release.
But, for automation, you can find unversioned files in the Assets section of each release here on GitHub.
