### ISSUE TITLE
Integrate Okta JWT verifier 

### ISSUE THREAD

**Issue by robomfeinberg** [smallstep/cli#150]
### What would you like to be added
Please look at adding Okta JWT verification. 
https://github.com/okta/okta-jwt-verifier-golang 

### Why this is needed
This would provide a more seamless verification with Okta.

**Comment by maraino** [comment]
I believe Okta OAuth 2.0 and OpenID Connect integration should work with us, but we haven't tested. I would be helpful to know if it's working or not.

@robomfeinberg can you check if Okta's OAuth 2.0 integration will work?

First you will need to configure an OAuth2.0 with OpenID Connect enabled in Okta and user the client id and secret in the `step-ca` configuration like:
```json
{
            "type": "OIDC",
            "name": "Okta",
            "clientID": "<client-id provided-by-okta>",
            "clientSecret": "<client-secret-provided-by-okta>",
            "configurationEndpoint": "https://<yourOktaDomain>/.well-known/openid-configuration",
            "domains": ["<your-domain>"],
}
```
If you are using a custom authorization server `configurationEndpoint` will look like `https://<yourOktaDomain>/oauth2/<authServerId>/.well-known/openid-configuration`

If the integration works you should be able to create X.509 certificates with your email on it running:
```sh
step ca certificate joe@domain.com joe.crt joe.key
```

**Comment by robomfeinberg** [comment]
@maraino  The redirect_url is always 127.0.0.1 even if I don't have one setup in my app. 

`https://dev-216537-admi.okta.com/oauth2/v1/authorize?client_id=0oa1d4s8uySXXXzHb357&code_challenge=oFJeS-B3biJYdDrJb2kQcOV-IgFu74aVI3UcAE2sFds&code_challenge_method=S256&nonce=73d358a9f420c408cd3a9b50446bbbf62edd5df0a5f45dXXXX&scope=openid+email&state=2fb7p9yVZNUEySq2vqPJNs8e6WzVDPLa
`

**Comment by robomfeinberg** [comment]
I would also like to point out that when I run curl against the userinfo url I get an google output url. I don't have google set as a provisioner. 
```
#  curl -H"$(step oauth --oidc --header) https://dev-216537.okta.com/oauth2/v1/userinfo"                                                                               Cannot open a web browser on your platform.

Open a local web browser and visit:

https://accounts.google.com/o/oauth2/v2/auth?client_id=1087160488420-8qt7bavg3qesdhs6it824mhnfgcfe8il.apps.googleusercontent.com&code_challenge=lU_P1pd2KwHAg8FP_39gn2FSU6ITgxJwFx1zocCYfF4&code_challenge_method=S256&nonce=1c834ad42f39c7b2a73b6dfeadc83f364525d522c6eda6d27cada95edc0918af&redirect_uri=http%3A%2F%2F127.0.0.1%3A45837&response_type=code&scope=openid+email&state=7IqknjfjLhkEJiOz7qhXv7mgUfUIF4CD
```

**Comment by maraino** [comment]
@robomfeinberg we set up the redirect_uri to 127.0.0.1 because we need the get the response and exchange the authorization code for the token.

`step oauth` command is not integrated with the CA and by default it just uses Google as the provisioner. If you want to use okta you will need to use something like:
```
step oauth --oidc --header --client-id=<client-id> --client-secret=<client-secret> --provider https://dev-216537-admi.okta.com
```

If you want to check if the Okta's OIDC provider works on the CA you can use `step ca token you@acme.com`, if you pick the Okta's provisioner it will open a browser and print the OIDC token (id_token).

**Comment by maraino** [comment]
I've created an okta account and Web App, but Okta doesn't allow you to use a random port to do the callback, against the recommendation in https://tools.ietf.org/html/rfc8252#section-7.3. So a fixed port is required.

We also have a way to get the OIDC token this way, but is not currently integrated into a certificate flow, but to get the token we can use `step oauth` (but not `step ca token`), so let's say you configure the redirect uri to http://127.0.0.1:10000, we can get the oidc token with
```
step oauth --client-id <client-id> --client-secret <client-secret>\
  --provider https://<account>.okta.com 
  --bare --oidc --listen 127.0.0.1:10000
```
That would be the token used to get a certificate from the CA, but sadly the token has a version property "ver" as an integer instead of a string, and step crashes.

So right now Okta is not compatible but we can work on this issue to make it compatible in the future.

**Comment by sourishkrout** [comment]
The OIDC provisioner is now compatible with Okta
