### ISSUE TITLE
Change OIDC response URL from 127.0.0.1 to localhost

### ISSUE THREAD

**Issue by janknieling** [smallstep/cli#169]
Please change the OIDC response URL from http://127.0.0.0 to http://localhost because 127.0.0.1 causes errors with Microsoft Azure AD because they arent allow to set an application response URL without https to any target except http://localhost

With 127.0.0.1 as reply address you will receive the following errors:

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'XXXXXXXX'.

**Comment by maraino** [comment]
Hi @janknieling, we cannot do that because the [RFC](https://tools.ietf.org/html/rfc8252#section-7.3) recommends the use of 127.0.0.1, and [here](https://tools.ietf.org/html/rfc8252#section-8.3) it even says that the use of `localhost` is NOT RECOMMENDED.

Microsoft has changed something because we have an AD application configured with http://127.0.0.1.

Regarding solutions, we can work on a workaround but at the same time, you should also contact Microsoft and ask about it with the links to the RFC I provided above.

**Comment by janknieling** [comment]
I think a workaround is the easier solution because I don't think that Microsoft will change anything on its Azure AD plattform.
On the screenshot below you can see the issue.
![Smallstep_AzureAD_App_error](https://user-images.githubusercontent.com/22558802/66167467-7eb82600-e63a-11e9-887c-7725c95eb382.png)

**Comment by mmalone** [comment]
Yea the weird thing is we tested this in Azure AD a few months ago and it worked. So this seems like a recent regression. This is a particularly silly exception to BCP since there’s really no reason to accept localhost but not 127.0.0.1. If this is a regression and MS can fix it that’d be really nice. If they have a good reason not to I’d like to hear it. The hard part is getting their attention.

That said, we’ll definitely do a workaround to support Azure AD if we need to.

In the meantime it should be pretty easy to patch [the oauth subcommand](https://github.com/smallstep/cli/blob/master/command/oauth/cmd.go) to do what you want. Building is easy (make bootstrap && make).

Shenanigans!

**Comment by maraino** [comment]
Hi @janknieling, you can enable `http://127.0.0.1` using the Azure CLI (`az`):

```sh
az ad app create --display-name mytestapp --reply-urls http://127.0.0.1
```

Once you do that you will be able to see your new app in the portal, you will need to create a secret in app "Certificate & secrets" section and you will be ready to go, the provisioner configuration should look like:

```json
{
            "type": "OIDC",
            "name": "Microsoft - Or your provisioner name",
            "clientID": "<client-id>",
            "clientSecret": "<client-secret>",
            "configurationEndpoint": "https://login.microsoftonline.com/<tenant-id>/v2.0"
}
```

I wll leave this issue open to create a workaround in our cli.
