### ISSUE TITLE
Unable to read CommonName for certificates created using CertBot

### ISSUE THREAD

**Issue by dopey** [smallstep/cli#176]
### Subject of the issue
Unable to read CommonName for certificates created using CertBot

### Steps to reproduce
```
sudo REQUESTS_CA_BUNDLE=$(step path)/certs/root_ca.crt certbot certonly -n --standalone -d foo.internal --server https://ca.smallstep.com:8080/acme/my-acme-provisioner/directory --agree-tos --email max@smallstep.com
```
The `step certificate inspect` the generated certificate.
```
sudo step certificate inspect /etc/letsencrypt/live/foo.internal/fullchain.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 294881486986066264314113602740159988519 (0xddd81bcc1ba1f37b2fcc49d894674327)
    Signature Algorithm: ECDSA-SHA256
        Issuer: CN=Smallstep Intermediate CA
        Validity
            Not Before: Oct 16 22:11:42 2019 UTC
            Not After : Oct 17 22:11:42 2019 UTC
        Subject:         Subject Public Key Info:
            Public Key Algorithm: RSA
                Public-Key: (2048 bit)
                Modulus:
```
### Expected behaviour
There should be a common name. 

### Actual behaviour
There is no common name.

### Additional context
If you use `step certificate inspect --short` there is a Subject common name but it is multi-line, as though there are special characters that the step utility is not handling correctly.

**Comment by mmalone** [comment]
Are you sure there _is_ a common name in the issued certificate? It's possible that certbot doesn't ask for one in its CSR so `step-ca` doesn't include one in the certificate?

If that's the case, I'm not convinced that this is an _issue_, per se, since CNs have been deprecated by CA/Browser Forum. It's likely that CNs will start disappearing from Web PKI certificates soon. So, _if_ certbot is requesting a certificate without a CN I don't think it'd be wise for us to assume that's _not_ what it wants and add one.

I did notice this when I was playing around with ACME and I do think there's one small bug. If I'm right and the certificate doesn't contain a CN at all then we need to update the `step certificate inspect --short` formatting to reflect that. It looks like that command currently prints something like:

```
...
Subject: <common-name>
         <san-1>
         ...
         <san-N>
...
```

But it doesn't check to see if there's a CN at all. So if you don't have a CN it tries to print one anyways, and just prints the empty string. You end up with something like:

```
...
Subject: 
         smallstep.com
...
```

We should fix this formatting to not print the empty CN. It should look like this:

```
...
Subject: smallstep.com
...
```

**Comment by dopey** [comment]
Hey @mmalone. Sorry, I ended up taking the convo to gitter, but you've basically nailed what was happening. `certbot` does not set a subject CN by default.

**Comment by dopey** [comment]
New issue - https://github.com/smallstep/cli/issues/178
