### ISSUE TITLE
Not possible to fully automate ca init with existing encrypted root key

### ISSUE THREAD

**Issue by ZacharyJoswick** [smallstep/cli#220]
### Subject of the issue
When attempting to use the `step ca init` command with an existing encrypted key, it is not possible to fully automate this process as the command will always ask for the password to decrypt the key file even if one is specified using the `--password-file` option. Additionally, this module doesn't appear to accept input from stdin for this value, so one is relegated to manually providing this value at runtime. The result is that automated ca initialization cannot be fully automated using tools like docker or ansible in this specific case. 

### Your environment
* OS - Ubuntu
* Version - 16.04
(This should be applicable to all operating systems and versions)

### Steps to reproduce
1. Initialize a step ca as per documentation in the getting started guide. 
2. Copy the generated root certificate and key only out of STEPPATH into a temporary location
3. Remove entire STEPPATH directory
4. Attempt to recreate the ca by providing all necessary arguments on the command line:

        step ca init --name="Example CA" \
          --password-file="./password.txt" \
          --key="./root_ca_key" \
          --root="./root_ca.crt" \
          --dns="localhost,127.0.0.1" \
          --address="0.0.0.0:443" \
          --with-ca-url="localhost:443" \
          --provisioner="Automated Provisioning" \
          --provisioner-password-file="./provisioner_password.txt"
5. The above command will then prompt for a password to decrypt the root_ca_key and automation scripts will either stop here, or error out

I created a repository with a script and dockerfile which demonstrate the issue. You can find it along with instructions for use [here](https://github.com/ZacharyJoswick/step-ca-init-issue).

### Expected behaviour
If the `--password-file` argument is provided along with the `--key` and `--root` arguments, it should be used to decrypt the file rather than requiring manual input. 

### Actual behaviour
The prompt `Please enter the password to decrypt <root_ca_file>:` is printed and requires user input.

### Additional context
It appears that this issue stems from the file [init.go](https://github.com/smallstep/cli/blob/e050b985e0b2f5766c8674c2ff0a433515f73ba0/command/ca/init.go#L106) which, when parsing a key file using the `Pemutil.Read` and subsequently the `Pemutil.Parse` method, does not pass in a password option as the password file parsing happens later in the code. As such, there is no way to use an encrypted key and not have it ask for a password. A potential solution would be to parse the `password-file` argument before the `key` argument and if populated pass it into the `Pemutil.Read` function as an option. I believe this will resolve the issue.

While I understand this situation is somewhat unusual, it is important to our specific use case. We are deploying step-ca to an air-gapped system that once deployed will not be accessible to any of our engineers. As such, we need to make provisions for updating the system reliably without ever working on the system directly. As such, we are establishing a set of tools that will completely redeploy the operating system and all applications rather than attempting to incrementally update. However, we intend for this system to serve as the CA for the air-gapped network, and we are not intending on redeploying the os to all machines on the network, so we are creating a common root certificate which is installed on all machines, and then at the time of provisioning recreating the intermediate and application certificates. In this manner, the other machines on the network should trust the deployed system and all applications running on it without requiring updates to their root certificates. However, as we need to protect the common root certificate, we are intending to store the key in an encrypted format and keep the password for the key on an external security device. Then, during system installation, we will acquire this password, pass it into step ca init to create the intermediate certificates, then discard any password information. As stated previously this all has to be fully automated with zero human intervention, so not being able to automate this process is somewhat blocking for us. 

If desired I could put together a pull request to fix the issue, however, my knowledge of go is basic at best, and I am unsure if there are larger ramifications to a simple reordering of the argument parsing and the passing of the options structure. Additionally, if the root key's password is different from the desired intermediate password (as is best practice) then this solution would not work.

**Comment by maraino** [comment]
> ### Expected behaviour
> If the --password-file argument is provided along with the --key and --root arguments, it should be used to decrypt the file rather than requiring manual input.

@mmalone That would mean, that the intermediate certificate will be encrypted using the same password, is this the expected behavior that we want. More complex configuration can always achieved manually.

**Comment by mmalone** [comment]
Hi @ZacharyJoswick, interesting use case. There's a lot going on here!

You probably know most of the following, but let me recap just to make sure we're all on the same page...

When you run `step ca init` the `--password-file` is used to _encrypt_ your root & intermediate CA keys (`~/.step/secrets/root_ca_key` and `~/.step/secrets/intermediate_ca_key`, respectively). The `--provisioner-password-file` is used to _encrypt_ your provisioner private key (the default JWK provisioner uses a key pair, and the password-encrypted private key is escrowed by the CA). I know that's a mouthful, but the point is that these two flags are being used to _encrypt_ the new artifacts being produced.

When you're creating an entirely new PKI from scratch, passing these two flags along with a few others will make `step ca init` run non-interactively like you want. You're running into trouble because you're _also_ passing in the `--key` (and `--root`) flags to use an _existing_ root CA/key instead of generating a new one. So...

What's happening here is that the `--key` you're passing in (`./root_ca_key`) is encrypted, and there's no way to pass a flag directly into `step ca init` to _decrypt_ that key non-interactively. We could add a flag for that, but I'm a bit reluctant to add another password-related flag for such a specific use case (if we get more people asking about this that would probably change my mind). Instead, we could assume that the password you're using for encrypting the new artifacts generated by `step ca init` is the same as the password that was used to encrypt your existing `root_ca_key`. That might be true for you, but I don't think we can safely assume that in general. So that might confuse matters further.

Luckily, I think we've got a workaround that should work for you here and is more explicit. The key insight is that, if you pass an _unencrypted_ `root_ca_key` into `step ca init` this prompt will go away. I'm guessing you don't want to leave your unencrypted root private key lying around on disk though. Instead, we can use an incantation of `step crypto key format` to non-interactively decrypt your `./root_ca_key` and print it to stdout, then use bash process substitution to pass that directly into `step ca init` without storing the file permanently on disk anywhere.

I just tested this locally. The complete command is:

```
step ca init --name foo \
  --password-file <(echo "foo") \
  --provisioner-password-file <(echo "foo") \
  --with-ca-url "localhost" \
  --address ":443" \
  --dns "localhost" \
  --provisioner "mike@example.com" \
  --key <(step crypto key format \
                  --no-password --insecure --pem \
                  --password-file <(echo "bar") ./root_ca_key) \
  --root ./root_ca.crt
```

The new part is the `<(step crypto key format ...)` stuff being passed into `--key`. It's a mouthful, but it works.

A couple notes worth mentioning:

1. When you run this command `step ca init` will _re-encrypt_ your `./root_ca_key` using the `--password-file` passed to `step ca init`. If that password is known by less trusted components you might not want that. The CA doesn't actually _need_ the root signing key (it signs with the intermediate) so you can actually `rm ~/.step/secrets/root_ca_key` immediately after running `step ca init` and close that hole. If you want to prevent this file from being written altogether there's a more complex workflow you can use. Lemme know if you want more info on that.
2. We have HSM support for the CA coming soon (see https://github.com/smallstep/certificates/tree/kms). We think that an HSM/TPM-backed private key is the best way to manage a PKI non-interactively. It does require hardware support though.

Sorry for the wall of text, but hopefully this works for you. If not, lemme know and I'll noodle on it some more!

I internet stalked you a little bit and it looks like you're doing some cool stuff. If you ever want to hop on a call and chat we'd love to hear more details and try to answer any other questions you might have. Shoot me an email if you're interested. I'm mike at smallstep.

Also, **GO HOKIES!**

**Comment by ZacharyJoswick** [comment]
Good morning @mmalone. First off, thank you for getting back to me so quickly on this. 

The good news is that your proposed fix does solve my problem.

I'll is the first to admit that I'm a beginner at this type of configuration and realistically PKI infrastructure in general, so I appreciate you explaining everything as you did. Historically, any certificate-based configuration has been handled by our IT department using commercial certificates and the like, then just distributed as needed to our edge ingress nodes. But as I mentioned in my original post, this is an offline system and is completely separate from our company network, so that responsibility now falls to me. It's definitely been a bit of a learning experience.

I completely understand your position on the command line flag and since the issue can be mitigated using your bash trick I don't see a reason it would ever be needed. On the subject of your fix, I'm a bit disappointed in myself for not figuring that out, it's just so perfectly obvious. I did try and use the crypto command earlier, but I was not using it through bash process substitution and instead was writing it out to disk. I didn't go down this route as, as you said, I did not want the unencrypted private key being written to disk (we have some advanced logging tools which maintain a log of disk writes and for new files, it records the contents. This would then leave the key sitting unencrypted in a log file which is not ideal). I'm ok with the root_ca_key being written back to disk and promptly deleted, I think for our application as long as the data is encrypted there are no issues with that approach and we don't need to go down the route of intercepting it before it reaches disk.

I think one of the reasons I didn't initially think of using the step crypto approach inline was the wording in the help menu for `step ca init` where the description for the argument is: `The path of an existing key file of the root certificate authority`. I read this as requiring explicitly a file path and a file on disk (I've seen other programs that don't have logic in place to parse the contents of files passed through stdin, just the filenames) but its good that this is not the case. If anything it might be useful to either edit this message or provide an example in the help menu/documentation, although I expect that there are very few people using step in a manner where this matters.

As for the HSM, I completely agree that its the best way forward. Once we get everything initially set up I think we will go down that route. We were already looking at doing something similar but handling the HSM ourselves, so it's great that you guys are supporting that natively.

Also, after we get a bit further down the line and have some time to test out the system id be more than willing to jump on a call with you and your team to discuss further. 

Thank you again for your assistance. I'll close this issue for now as everything seems to be working as intended.

**Comment by mmalone** [comment]
Glad it worked, and happy to assist as you get up to speed. Definitely don’t feel bad about not finding this solution. It was super unintuitive. I actually had to ask the team at standup. I was trying to decrypt the key using `step crypto change-pass` but that won’t print to stdout. Someone else came up with the idea of using `step crypto key format`.

Regarding the `step ca init` command stating that `-key` must be the path to a file on disk: this is actually correct. Bash process substitution — the `<()` (or `>()`) syntax — makes the output of the subcommand in the parenthesis “act like a file”. Try `cat <(echo “foo”)` and you’ll see what I mean. Then try `echo <(echo “foo”)` or `ls -lias <(echo “foo”)`. It’s pretty magical, and pretty awesome because it solves the problem you’re describing in general for all of those commands that only take files as input. I just learned this trick a couple years ago and now I use it daily!

Since this actually _is_ “creating a file” you probably should verify that it doesn’t interact unfavorably with the logging system you’re describing. My guess is that it isn’t, since the files being created are not normal files. But I don’t know all of the implementation details here.

HSM support just hit master today, so it’s definitely gonna make next release!

Feel free to open another issue or drop us a line [on gitter](https://gitter.im/smallstep/community) if you have any other questions. And let’s definitely schedule a call when you’re ready!
