### ISSUE TITLE
Do not use UID/GID 1000 in docker

### ISSUE THREAD

**Issue by retnikt** [smallstep/cli#292]
### Subject of the issue
In the [Dockerfile](https://github.com/smallstep/cli/blob/aac2566/docker/Dockerfile), the user is created with UID 1000 and GID 1000. This is difficult, because the first user on all host systems use 1000, which can cause headaches. Particularly with `step` and the sensitive nature of its CA files, it is often desirable to have files on the mounted `/home/step` volume readable only by root on the host system, but in order to use this inside the container, this directory must be owned by UID/GID 1000.
 
To solve this you should change the UID/GID to something high and random like 20395. (this essentially requires the use of the `-l` flag in `adduser` - see [here](https://github.com/moby/moby/issues/5419)). Unfortunately this constitutes a **breaking change** (though you can workaround it by stopping the container and running `chown -R 20395:20395 /path/to/step/on/host`

### Steps to reproduce
Run the Docker image with an explicit volume, e.g. `docker run -v /path/to/step:/home/step smallstep/cli`, where you want `/path/to/step` to be unreadable by ordinary users on the host system, but owned by the correct user inside the container.

### Expected behaviour
The container should use an arbitrary high UID and GID for the `step` user, like 20395 (just picked [randomly](https://xkcd.com/221) now)

### Actual behaviour
It uses 1000.

Can submit PR.

**Comment by retnikt** [comment]
While we're at it, can we remove the random blank line at the top of the Dockerfile?

**Comment by maraino** [comment]
I removed the blank line and I'm adding this issue to our backlog. 

One option to solve this in your side is use our image as builder, and just copy `/usr/local/bin/step` into the new image.

**Comment by maraino** [comment]
Hi @retnikt, I've been thinking about this and I see your point, but because of the backward compatibility problem I'm gonna close it as a won't fix. 

Right now one of the most common cases to use the step-cli container would be to run `step ca init` and create a pki to be used by the `step-ca` container. If we make the change we'll be forcing everybody using this flow, or expecting the files to have the uid 1000 to use the root user and chown them.

And at the same time, docker already allows you to run the docker container as root, and create the PKI with your necessary permissions. There's other options like creating your own container using step-cli as the base one, but this is probably easier:

```sh
$ docker run -it --user root:root -v my-volume:/home/step smallstep/step-cli:latest /bin/bash
bash-5.0# step ca init
...
bash-5.0# chown -R 1234:1234 *
```

With these two commands, you can have all the files in `my-volume` owned by the user that you want.

I have also committed a change #292 to make the uid and gid docker build arguments, so it's a little bit easier to build your own image using the same docker file:

```
$ docker build --build-arg STEPGID= 20395 --build-arg STEPUID= 20395 -t mariano/step-cli -f docker/Dockerfile .
```
