### ISSUE TITLE
Is there a way to generate a CSR from an existing Private Key?

### ISSUE THREAD

**Issue by christian-posta** [smallstep/cli#311]
Not seeing how I'd be able to do that. the `step certificate create -csr` seems to expect to create a new private key

**Comment by dopey** [comment]
Thanks for opening an issue! Yep, this is definitely something that's currently missing. We'll need to add it.

Do you mind giving a bit of insight into the use case? You have keys you'd like to use, that much I understand. But is that a requirement from some other software? Is it because `step` isn't able to generate the exact keys you want to use?

**Comment by christian-posta** [comment]
For sure! I was investigating options for cross-signing intermediate CAs and just exploring the tooling you all have created. It's been a pleasure to work with btw!

**Comment by dopey** [comment]
Hey, that's very kind, thanks! 

Currently this is on our mid-term roadmap. But if it becomes a blocker for you, please let us know and we can see about fast-tracking it. 

And, if anyone finds this and is looking for ways to contribute, we definitely encourage PRs from the community and are happy to help with guidance. There are a number of commands in the cli that take pub and priv key arguments, so there are plenty of examples to work from.

**Comment by dopey** [comment]
Hey @christian-posta I think this can already be done using the `--key` flag. E.g. `step certificate create --csr --key foo.key foo foo.csr`.

Going to close this issue but please let me know if I'm missing something and I'll reopen.
