### ISSUE TITLE
Enable a flag to not require a password for p12 file

### ISSUE THREAD

**Issue by carpenike** [smallstep/cli#414]
### What would you like to be added
In order to support certain automated functions for certificate packaging and then import into the Windows Cert Store,  `step certificate p12` should allow for no-password to be required.

Something like an `--insecure` or `--no-password` parameter option.

**Comment by carpenike** [comment]
Example automated renewal process on Windows:

Task Scheduler process:

`step ca renew --daemon --exec "powershell.exe cert-import.ps1" client.crt client.key`

Cert-Import powershell script:

```
## Renew Certificates with Step CA
$stepBinary = "c:\tools\step-ca\step.exe"
$cert = "C:\tools\step-ca\client.crt"
$certKey = "C:\tools\step-ca\client.key"
$certP12 = "C:\tools\step-ca\client.p12"
$passwordFile = "c:\tools\step-ca\password.txt"
$certStoreLocation = "Cert:\CurrentUser\My"

Write-Verbose "Convert cert files to p12"
& "$stepBinary" certificate p12 --password-file=$passwordFile -f $certP12 $cert $certKey

Write-Verbose "Grab Password and store as Secure String"
$pass = Get-Content $passwordFile | ConvertTo-SecureString -AsPlainText -Force

Write-Verbose "Import P12 Cert into $certStoreLocation"
Import-PFXCertificate -FilePath $certP12 -Password $pass -CertStoreLocation $certStoreLocation
```

In this scenario, the p12 is packaged because Windows requires the certificate and key to be paired together for an import. PowerShell would support an import with no password, but the step ca command does not allow for it.

**Comment by mmalone** [comment]
> Something like an --insecure or --no-password parameter option.

Don't have much to add, but wanted to clarify that we use `--insecure` when the combination of flags you're using (or omitting) makes a particular incantation insecure. For example, `--insecure` is required if you run `step crypto jwt verify` without passing in the `--alg` flag because, without an explicit algorithm, JWT verification is susceptible to algorithm downgrade attacks (one of the algorithms is "none"), which makes that incantation insecure. We also have a `--subtle` flag that's like `--insecure`, but it's used for stuff that's not necessarily _insecure_, but have subtle security implications. It's a milder warning, basically.

So these flags are both gates to prevent misuse. The idea is that they force the user to explicitly acknowledge that they know what they're doing. So, if `--no-password` is insecure, we'd probably want to require _both_ `--no-password` and `--insecure` for this subcommand.

**Comment by carpenike** [comment]
Yup I would agree and that makes sense!

**Comment by maraino** [comment]
@carpenike I'm looking at the RFC and there's always a way to encrypt the contents, either using a asymmetric key pair or the more common password-based encryption. Other tools like openssl, keytool force you to use a password; and the package that we use to encode to PKCS#12 too. But the password can be the empty string.

Can you test if an empty string password works for your use case?

**Comment by carpenike** [comment]
How would I pass the empty string to the command? I tried with an empty file but it didn't work.

**Comment by maraino** [comment]
@carpenike Just press the enter key when `Please enter a password to encrypt the .p12 file:`. Just to know if the certificate created with an empty string password will work for the rest of your flow.

**Comment by carpenike** [comment]
Sorry for the delay! Yes it works with just pressing enter when prompted:

```
PS C:\tools\step-ca> step certificate p12 -f client.p12 client.crt client.key
Please enter a password to encrypt the .p12 file:
Your .p12 bundle has been saved as client.p12.
```
