### ISSUE TITLE
New homebrew 3.0 package

### ISSUE THREAD

**Issue by alanchrt** [smallstep/cli#421]
For Silicon Mac.

https://brew.sh/2021/02/05/homebrew-3.0.0/

**Comment by tashian** [comment]
Go 1.16 was released today with ARM64 support, so I think this is only blocked on us upgrading to that.

**Comment by tashian** [comment]
I don't think this is blocked after all, because Homebrew builds the official binaries for us.
If I understand correctly, I think all we need to do is update our Homebrew build tomorrow when we release, and their bot will attempt an `arm64` build. If it works, they will include that binary in the bottle.
@dopey & I are scheduled to look at this tomorrow.

**Comment by dopey** [comment]
This is done. We have arm64 builds for macos in our releases.
