### ISSUE TITLE
Uninstall script leaves issues with Windows Terminal

### ISSUE THREAD

**Issue by modem7** [smallstep/cli#585]
### Subject of the issue
Uninstall script leaves issues with Windows Terminal.

### Your environment
* OS - Windows
* Version - 10

### Steps to reproduce
Installed via:
```
curl.exe -LO https://dl.step.sm/s3/cli/ui-cli-install/install-step.ps1
powershell -ExecutionPolicy Bypass -File "install-step.ps1"
```

Uninstalled via:
`powershell -ExecutionPolicy Bypass -File "uninstall-step.ps1"`

With it installed, the error message does not come up, path is added into Windows env path.
With it uninstalled, env path is removed, but error remains in Windows Terminal SSH sessions.

![image](https://user-images.githubusercontent.com/4349962/142648513-3e15d04f-c874-4523-b02c-aacd4dd7e691.png)

![image](https://user-images.githubusercontent.com/4349962/142649223-3280226e-6040-4f0d-92ae-e88ad7b01206.png)

### Expected behaviour
No remnant of cli-client should remain.

### Actual behaviour
See SS

### Additional context
Windows Terminal from Microsoft Store.
Error does not occur in Putty.
Error does not occur in Windows Terminal if using Powershell, Git, or Command Prompt tabs.
Reinstall of WT does not resolve. Nor does recreating SSH profiles.
Current $env:PATH:
![image](https://user-images.githubusercontent.com/4349962/142649950-2e7fafed-ddf4-47cd-bf0d-af9f3ff703e8.png)

**Comment by modem7** [comment]
Resolved.

Looks like `C:\Users\<username>\.step` was still in place.

Once deleted, the behaviour disappears. 

Not closing issue at this time as this needs to be addressed in uninstall script.

**Comment by mmalone** [comment]
Interesting. I understand how we got here: from our perspective, the `~/.step` directory is a configuration bundle. It's created when you bootstrap into an authority (e.g., running `step ca bootstrap` or `step ssh config`) and you can actually have multiple configuration directories (you can override the default location by setting the `STEPPATH` env var). Since the install script doesn't create it, it _sort of_ makes sense that the uninstall script doesn't delete it.

That said, I think you're right. From a user's perspective I think deleting this directory is the right thing to do for most use cases. Unfortunately, I don't think it's completely safe to do _in general_. Maybe we should prompt the user during uninsntall to confirm that it's ok to delete the directory (and provide a flag to allow non-interactive uninstall). The trouble there is that most end-users aren't going to know what the heck the `~/.step` directory is, so it'll be hard for them to answer a prompt. If we go this route we'll have to choose copy carefully.

**Comment by modem7** [comment]
Agreed from that perspective.

Maybe a prompt such as "would you like to delete user preferences? Y/N" and/or "Would you like to keep/backup user preferences", then if backed up, can either a) keep folder in ~./step or backup to the user folder under ~/stepbackup (or similar) which the installer can check for and restore. 

This would in theory allow for both use cases, whilst still keeping the system pre-install with the option to not throw away existing configs with a minor edit in install + uninstall scripts.

**Comment by tashian** [comment]
@modem7 I just committed a small update to the uninstall script, that optionally removes the .step folder.
Thanks for the report.

**Comment by modem7** [comment]
Perfect! Thank you!
