### ISSUE TITLE
ca init: does not accept IPv6 addresses

### ISSUE THREAD

**Issue by jpds** [smallstep/cli#605]
### Subject of the issue

`step ca init` does not accept IPv6 addresses as valid.

### Your environment

* Version - 0.18.0

### Steps to reproduce

```
step ca init
✔ Deployment Type: Standalone
What would you like to name your new PKI?
✔ (e.g. Smallstep): Test
What DNS names or IP addresses would you like to add to your new CA?
✔ (e.g. ca.smallstep.com[,1.1.1.1,etc.]): 1.1.1.1
What IP and port will your new CA bind to?
✔ (e.g. :443 or 127.0.0.1:443): :443
What would you like to name the CA's first provisioner?
✔ (e.g. you@smallstep.com): test@example.com
Choose a password for your CA keys and first provisioner.
✔ [leave empty and we'll generate one]: 

Generating root certificate... done!
Generating intermediate certificate... done!
...
```

IPv6 is not recognized as valid (taking the [example one from Wikipedia](https://en.wikipedia.org/wiki/IPv6_address#Representation)):

```
$ step ca init
✔ Deployment Type: Standalone
What would you like to name your new PKI?
✔ (e.g. Smallstep): Test
What DNS names or IP addresses would you like to add to your new CA?
✔ (e.g. ca.smallstep.com[,1.1.1.1,etc.]): 2001:0db8:85a3:0000:0000:8a2e:0370:7334
2001:0db8:85a3:0000:0000:8a2e:0370:7334 is not a valid DNS name
```

**Comment by whalehub** [comment]
I encountered the same issue earlier today. It looks like compressed (`2001:db8:85a3::8a2e:370:7334`) and bracket-delimited (`[2001:db8:85a3::8a2e:370:7334]`) IPv6 addresses are not accepted by `step ca init` either.

**Comment by whalehub** [comment]
@jpds I just discovered that you can specify a **bracket-delimited** IPv6 address when running `step ca init` non-interactively, e.g.:
```
step ca init --deployment-type="standalone" --name="Test" --dns="1.1.1.1" --dns="[2001:db8:85a3::8a2e:370:7334]" --address=":443" --provisioner="test@example.com"
```
It's not a fix for the underlying problem, but at least it's a workaround for now.

**Comment by hslatman** [comment]
I've opened a PR in [https://github.com/smallstep/cli-utils](smallstep/cli-utils) to allow anything that can be parsed as an IP as a DNS in the CLI: https://github.com/smallstep/cli/issues/605. Will create a PR for the CLI after it's approved.

**Comment by whalehub** [comment]
> Unlike what's described above, I was able to provide a bracketed IPv6 in the CLI. On the one hand this contradicts what @whalehub mentioned, but it is in line with the workaround in which the bracketed IPv6 is provided using a flag. The same validation logic is used for both cases, so that checks out.

@hslatman That's odd, when I tried it again today, it worked in the interactive version as well. Maybe when I tested it yesterday, I accidentally copied an additional invisible character from the website I got it from.

**Comment by hslatman** [comment]
@whalehub Sounds very probable, indeed.

Still makes sense to me to make this easier for users, though 😄

**Comment by hslatman** [comment]
While the changes in https://github.com/smallstep/cli-utils/pull/13 are approved, I found that just allowing IPv6 addresses without brackets is not going to work without additional changes in either the CLI and/or `step-ca`. The issue is related to the certificate that the CA generates for its own HTTPS handler to serve its API endpoints and validation of this certificate by `step-cli`. There are two ways to fix this:

Option 1 is to normalize the IPv6 address without brackets in the configuration. This would result in the CA creating a self signed certificate for the IP SAN of the IPv6 address (i.e. ::1) automatically. This requires a small change in the CLI that ensures that IPv6 addresses in the CA URL are patched with brackets if not provided (which is the case by default, if read from the configuration file).

Option 2 is to normalize IPv6 addresses to always be bracketed in the configuration. This will automatically result in the right CA URL being used by `step-cli`, but requires a change in how the CA creates the certificate to use for its own API. This needs to include the IP SAN corresponding to the IPv6 address in brackets instead of the DNS one (which is what is generated for an [::1] type of IPv6 address.

I think the first option is the cleanest from a user perspective. The CA will (only) use a proper IP SAN in its certificate and there are only changes in the CLI. Also the paths that configurations are stored in, won't contain `[...]`, which is slightly easier to use (although that may change soon). 

WDYT, @dopey?

**Comment by hslatman** [comment]
This one took a bit longer than expected, as we had to ensure that IPv6 hostname representations had to be handled consistently everywhere a hostname is required, such as in URLs, and the same IPv6 addresses as IPs when used as a SAN. It should now be fixed.
