### ISSUE TITLE
Add optional SHA1 fingerprint output for certificates

### ISSUE THREAD

**Issue by Delapouite** [smallstep/cli#611]
Hello

### What would you like to be added

Currently the `step-cli certificate fingerprint foo.pem` command only outputs the fingerprint as a SHA256 hash. It would be convenient to have an option to display a SHA1 fingerprint instead.

### Why this is needed

Azure Iot Hub services display the fingerprints as SHA1 hashes on the Azure portal, so it's not easy to compare both types of fingerprints.

Thanks.

**Comment by dopey** [comment]
Note for self (`step certificate format internal.crt | sha1sum
627780a72c976c84a0c0ddd973e3e4cabe318456  -`)

**Comment by dopey** [comment]
Hey @Delapouite thanks for opening the issue! This is a great idea and I think we'd like to see this implemented with a `--hash` (or maybe `--alg`) flag that would default to sha256 but allow other algs like sha1sum.

We'll open this one up to the community as it should be an easy addition. If anyone is looking to pick this up and needs some guidance, definitely let us know.

Cheers 🍻

**Comment by Dev4522v** [comment]
Hey @dopey! I'd like to pick this issue up. Can you help me out in getting started?

**Comment by dopey** [comment]
Hey @Dev4522v, I'd be happy to. We'll be looking at making edits to this file: https://github.com/smallstep/cli/blob/master/command/certificate/fingerprint.go. What we want to do is add a flag to change the hashing algorithm - we can call the flag `hash`. This is a good flag to base it on: https://github.com/smallstep/cli/blob/6b23538520fc8c720b067bec2fb7fe630f8825f4/flags/flags.go#L20-L37. The default will be sha256. And then just change the sha algorithm used in the action depending on the flag. 

If you have questions about getting started developing in golang - look up `setting up a golang dev environment`. The steps should be pretty simple. I develop on MacOS and I've used `brew` to set up the few things I need.

Let me know if you have additional questions :) Good luck!

**Comment by Dev4522v** [comment]
Thanks for the reply @dopey! I have the golang development environment setup on my mac too. I needed some help understanding the fingerprint.go file. I understand go syntax but I am having difficulty figuring out what the file is exactly doing. Can you explain that or maybe setup a brief call (if convenient)?

Thanks. Looking forward to contributing.

**Comment by dopey** [comment]
The command `step certificate fingerprint` returns a "fingerprint" for a certificate. Try it out by running `step certificate fingerprint https://google.com`. It works on URLs or certificate files on disk. A "fingerprint" is just a hash over the data in the certificate. 

* In this section we pull a bunch of the flag values that were input in the CLI and instantiate variables (https://github.com/smallstep/cli/blob/master/command/certificate/fingerprint.go#L93-L99).
* Read the certificate from disk or pull it down from a URL (https://github.com/smallstep/cli/blob/master/command/certificate/fingerprint.go#L107-L120)
* `bundle` just means if there are multiple certificates in the file, return a fingerprint for each certificate, instead of just the first one.
* Finally, get the hashed fingerprint for each certificate and print the value to std out. https://github.com/smallstep/cli/blob/master/command/certificate/fingerprint.go#L126-L135

If you have specific questions about methods, let me know. The best way to get familiar and understand what the functions are doing is to just follow the code a bit.

For example, this method (https://github.com/smallstep/cli/blob/5ba202a75b65e61edf3986b40bf9407a4f054c8c/crypto/x509util/crt.go#L42) just uses sha256 by default. Either the method will need to change to accept a new argument, or we'll need to introduce a new method that does accept the argument to alter the hash function on demand.

**Comment by Dev4522v** [comment]
Thanks @dopey! I think I have a fair understanding of the task now. 

A question I'd like to ask before I get started: In the EncodedFingerprint method that you mentioned, I can see that the variable sum is being initialised as `sum := sha256.Sum256(cert.Raw)`. I am planning to add another argument alg (of type string) which will come from the value of the flag. This will be sha256 by default but to get the hashed fingerprints using other encryption methods like sha1sum which external package should I use? 
I found the sha256 package here https://pkg.go.dev/crypto/sha256. Can you help me figure out the methods I should use for sha1sum or any other encryption methods?

My idea is to add a flag alg (as mentioned above) which would be passed on to the EncodedFingerprint method as 
`func EncodedFingerprint(cert *x509.Certificate, alg string, encoding FingerprintEncoding) string { ` and then based on the value of the flag the encryption algorithm would be applied on the certificate.

I hope this works and sorry if I am asking too many questions. Thanks

**Comment by 1984gobrr** [comment]
Hi, I have made a PR for this issue :smile:  https://github.com/smallstep/cli/pull/652 

@dopey

**Comment by hslatman** [comment]
#652 was just merged. Thanks for contributing, @1984gobrr! 😄
