### ISSUE TITLE
Allow custom text the oauth responses

### ISSUE THREAD

**Issue by srinathman** [smallstep/cli#691]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Allow custom text in the oauth responses. For example, the success message is hard coded to: 

`<strong style='font-size: 28px; color: #000;'>Success</strong><br />Look for the token on the command line`

## Why is this needed?
In some situations this message can be very confusing for the user, especially when little or no user interaction in the command line is needed.

**Comment by dopey** [comment]
Hey @srinathman :wave: thanks for opening this issue!

Changing the message is somewhat complex because there isn't an obvious place in the code where this change should happen. It will require some design. However, we do allow the user to specify their own redirect URL where you could serve a web page with whatever content you choose.
The command `step oauth` (which implements an OAuth flow and returns an OAuth token) already has a flag to change the redirect URI -- `--redirect-url`.

When you run a command like `step ca certificate` and authenticate using an OIDC provisioner, under the hood the `step oauth` will be run to get the necessary token. You have two options to change the value of `redirect_url` in the downstream call to `step oauth`: 1) You can use an environment variable - `STEP_REDIRECT_URL=xxx step ca certificate` -OR- 2) you can set a value for `redirect_url` in your `$(step path)/config/defaults.json`.

**Comment by srinathman** [comment]
Thank you @dopey , I undertand the complexity and I guess the redirect_url option will do it for now.
Perhaps just adding a couple of cli parameters could to the job ?

**Comment by dopey** [comment]
I'll bring it up during our next open source meeting. 

We could have an additional flag like `--success-text` but I suspect there will be pushback on a few counts:
1. We're cluttering the CLI with additional flags that aren't strictly necessary (`--redirect-url` can already handle this).
2. This flag would only replace the default text and I'm sure that users would start asking for more complex HTML, in which case we'd be pointing them to the `--redirect-url` again.

**Comment by dopey** [comment]
After discussing with the team, our preferred solution here would be for users to use the `--redirect-url` flag, rather than new parameters.

Our reasoning is that it wouldn't necessarily be difficult to add those parameters to a single command like `step oauth`, but then users would want to use those parameters in other commands that use `step oauth` under the hood (any command that requires OIDC provisioner credentials) which would require us to thread these flags through a number of commands, thereby cluttering the CLI.
