### ISSUE TITLE
Add a `listenHost` option for OIDC provisioners, for Azure AD OIDC

### ISSUE THREAD

**Issue by ryanc-me** [smallstep/cli#715]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add a `listenHost` key for OIDC provisioners, which can be set to, e.g., `localhost`.

With this set, step-ca would continue using the current unused-port-lookup mechanism, but would instead bind to `<listenHost>:<random-port>`, instead of using `127.0.0.1`. For example, the final listen address might be `localhost:12345`.

Alternatively, maybe a simple boolean `listenLocalhost` key could be added, forcing step-ca to use `localhost` instead of `127.0.0.1` (maybe this is better - less prone to configuration issues?)

## Why is this needed?

Currently, for OIDC provisioners, if the `listenAddress` option is _not specified_, step-ca will bind to `127.0.0.1` on a random unused port. This is very handy because on Windows, [some ports are "reserved"](https://superuser.com/questions/1450103/reserved-ports-in-windows-1809) - from my understanding, these reserved ranges are semi-random (or update-specific). 

Effectively, we get a redirect URI that looks like: `http://127.0.0.1:<random-port>`. This generated listen-address is also used as the redirect URI for the provisioner.

However, Azure AD only supports redirect URIs that are either `HTTPS`, or are `http://localhost:<whatever>` - **`http://127.0.0.1` is not supported**. [See here for Microsoft's docs on this](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#supported-schemes).

To use Azure AD with step-ca, we currently need to hardcode a `listenAddress` that binds on `localhost`. However, that also disables the unused-port-lookup feature, which means that any Windows update may suddenly "reserve" the port we hardcoded. For example, I have been using port `"listenAddress": "localhost:60234"` - this worked fine for ~12 months, until a recent Windows update marked that port as "reserved", and broke my step SSH logins.

**Comment by ryanc-me** [comment]
Reference issue: #703

**Comment by maraino** [comment]
Hi @ryanc-me, you should be able to fix it adding this to your provisioner:
```
"listenAddress": "localhost:0"
```

This will force the `redirect_uri` to be like `http://localhost:52478`, where the port will be an unused one. The command executed will be like this:

```console
step oauth --oidc --bare --provider https://my.oidc/.well-known/openid-configuration --client-id foo --client-secret bar --listen localhost:0
```

Alternatively, and without `listenAddress` in the `ca.json`, you can define the `listen` flag in the `defaults.json` or use the environment variable `STEP_LISTEN`.

Feel free to reopen the issue if this doesn't solve your use case.

By the way, the RFC specifically recommends using 127.0.0.1 instead of localhost See [rfc8252#section-7.3](https://www.rfc-editor.org/rfc/rfc8252#section-7.3) and [rfc8252#section-8.3](https://www.rfc-editor.org/rfc/rfc8252#section-8.3). And if I'm correct, even if azure portal doesn't allow localhost, I remember being able to configure it using az, in case you prefer using the IP.

**Comment by ryanc-me** [comment]
Thanks @maraino, it looks like that will work nicely!

Also thank you for the tip about Azure, it looks like you _can_ allow `127.0.0.1`, [just not via the Azure web portal
](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#prefer-127001-over-localhost). Maybe that'll be useful for someone in the future.
